import unittest
from scoring_trace import ScoringTrace
from event_reasoner import EventReasoner
from explanation_engine import ExplanationEngine
from analytics import TimelineAnalytics

class TestExplainabilityEngine(unittest.TestCase):
    def test_scoring_trace_addition(self):
        """
        Verify that the traceback contributors sum up exactly to the final session score
        under various inputs.
        """
        test_inputs = [
            (0.85, 0.90, 0.80, 0.15, 95.0, 0.10),
            (0.50, 0.40, 0.60, 0.50, 70.0, 0.45),
            (1.0, 1.0, 1.0, 0.0, 100.0, 0.0),
            (0.10, 0.10, 0.20, 0.80, 20.0, 0.90),
            (0.75, 0.70, 0.70, 0.30, 85.0, 0.20)
        ]
        
        for conf, attn, foc, stress, integ, gaze_dev in test_inputs:
            score, contributors = ScoringTrace.calculate_session_trace(
                session_confidence=conf,
                session_attention=attn,
                session_focus=foc,
                rolling_stress=stress,
                integrity_score=integ,
                gaze_deviation_ratio=gaze_dev
            )
            
            total_calc = sum(contributors.values())
            self.assertEqual(score, total_calc, f"Contributors sum {total_calc} does not match score {score}")
            self.assertTrue(0 <= score <= 100)

    def test_inference_confidence_deductions(self):
        """
        Verify that inference confidence is appropriately reduced under low lighting,
        motion blur, landmark jitter, ROI instability, and partial face visibility.
        """
        metrics_all_ok = {
            "lighting_ok": True,
            "blur_ok": True,
            "landmarks_stable": True,
            "face_visible": True,
            "roi_stable": True
        }
        conf, reasons = EventReasoner.calculate_inference_confidence(metrics_all_ok)
        self.assertEqual(conf, 1.0)
        self.assertEqual(len(reasons), 0)

        metrics_dark_blurry = {
            "lighting_ok": False,
            "blur_ok": False,
            "landmarks_stable": True,
            "face_visible": True,
            "roi_stable": True
        }
        conf, reasons = EventReasoner.calculate_inference_confidence(metrics_dark_blurry)
        self.assertEqual(conf, 0.7)
        self.assertIn("low lighting", reasons)
        self.assertIn("motion blur", reasons)

        metrics_all_bad = {
            "lighting_ok": False,
            "blur_ok": False,
            "landmarks_stable": False,
            "face_visible": False,
            "roi_stable": False
        }
        conf, reasons = EventReasoner.calculate_inference_confidence(metrics_all_bad)
        self.assertEqual(conf, 0.2)
        self.assertEqual(len(reasons), 5)

    def test_ethical_safety_claims(self):
        """
        Verify that no absolute psychological claims (e.g. lying, depressed, anxious)
        are ever generated by the ExplanationEngine or Recruiter Summary.
        """
        exp_engine = ExplanationEngine()
        exp_engine.total_frames = 100
        exp_engine.gaze_center_count = 60
        exp_engine.gaze_left_count = 20
        exp_engine.gaze_right_count = 20
        exp_engine.pose_center_count = 70
        exp_engine.pose_down_count = 30
        exp_engine.speaking_count = 20
        exp_engine.low_lighting_frames = 50
        
        attn_exp = exp_engine.get_attention_explanation(72, 0.8)
        conf_exp = exp_engine.get_confidence_explanation(65, 0.8)
        integ_exp = exp_engine.get_integrity_explanation(95.0, 0.8)
        summary = exp_engine.generate_recruiter_summary(72, 95.0)

        all_text = " ".join(attn_exp["explanation"]) + " " + " ".join(conf_exp["explanation"]) + " " + " ".join(integ_exp["explanation"]) + " " + " ".join(summary)
        
        banned_words = ["lying", "deceiving", "liar", "depressed", "depression", "anxious", "anxiety", "dishonest"]
        for word in banned_words:
            self.assertNotIn(word, all_text.lower())

    def test_event_reasoner_causal_chains(self):
        """
        Verify that EventReasoner accurately generates causal factors for major events.
        """
        reasoner = EventReasoner()
        env_metrics = {"lighting_ok": True, "blur_ok": True, "landmarks_stable": True, "face_visible": True, "roi_stable": True}
        
        recent_states_attn = [
            {"attention": 0.3, "gaze": "Left", "head_pose": "Down", "speaking": False},
            {"attention": 0.2, "gaze": "Right", "head_pose": "Down", "speaking": False},
            {"attention": 0.1, "gaze": "Left", "head_pose": "Down", "speaking": False}
        ]
        
        reason_data = reasoner.reason_behavioral_event("Attention Drop", recent_states_attn, env_metrics)
        self.assertEqual(reason_data["event"], "Attention Drop")
        self.assertIn("off-screen gaze", reason_data["reason"])
        self.assertIn("head-down posture", reason_data["reason"])
        self.assertIn("speech inactivity", reason_data["reason"])

if __name__ == "__main__":
    unittest.main()
